version: '3'

dotenv:
  - ".env"

vars:
  CONTAINER_NAME: go-unittest-architecture-db
  MIGRATIONS_PATH: migrations

tasks:
  hello:
    cmds:
      - echo 'Hello World from Task!'
    silent: true
  db:run:
    cmds:
      - docker run --rm --name {{.CONTAINER_NAME}}
        -p 3306:3306
        -e MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
        -e MYSQL_DATABASE=$MYSQL_DATABASE
        -d mysql:latest
    silent: true
  db:connect:
    cmds:
      - docker exec -it {{.CONTAINER_NAME}} mysql -uroot -p$MYSQL_ROOT_PASSWORD $MYSQL_DATABASE
    silent: true
  db:stop:
    cmds:
      - docker stop {{.CONTAINER_NAME}}
    silent: true
  migrate:create:
    cmds:
      - migrate create -ext sql -dir {{.MIGRATIONS_PATH}} -seq {{.CLI_ARGS}}
  migrate:up:
    cmds:
      - migrate --path {{.MIGRATIONS_PATH}}
        --database "mysql://root:$MYSQL_ROOT_PASSWORD@tcp(localhost:3306)/$MYSQL_DATABASE"
        -verbose up
  migrate:down:
    cmds:
      - migrate --path {{.MIGRATIONS_PATH}}
        --database "mysql://root:$MYSQL_ROOT_PASSWORD@tcp(localhost:3306)/$MYSQL_DATABASE"
        -verbose down
  migrate:version:
    cmds:
      - migrate --path {{.MIGRATIONS_PATH}}
        --database "mysql://root:$MYSQL_ROOT_PASSWORD@tcp(localhost:3306)/$MYSQL_DATABASE"
        -verbose version
  migrate:force:
    cmds:
      - migrate --path {{.MIGRATIONS_PATH}}
        --database "mysql://root:$MYSQL_ROOT_PASSWORD@tcp(localhost:3306)/$MYSQL_DATABASE"
        -verbose force {{.CLI_ARGS}}
